---    
- name: Create directory layout
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items: "{{ web_directories }}"
  when: item | length > 0
     
   
- include_tasks: 
    file: vhost.yml